#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "onedark"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = false
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = false
  enable_statusline_mode = false
  statusline_unicode = false
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = false
  enable_statusline_bfpath = true
  enable_tabline_ft_icon = true
  info_symbol = 'i'
  error_symbol = "e"
  warning_symbol = '!'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = "ui"
  enable_cursorword = true

[[layers]]
  name = "edit"
  autosave_events = ['InsertLeave', 'TextChanged']

[[layers]]
  name="colorscheme"

[[layers]]
  name = "core"
  filetree_show_hidden = true
  enable_filetree_gitstatus = true
  enable_filetree_filetypeicon = true

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
  name = "github"

[[layers]]
  name = "operator"

[[layers]]
  name = 'git'
[[layers]]
  name = 'VersionControl'

[[layers]]
  name = "sudo"

[[layers]]
  name = "telescope"

[[layers]]
  name = "treesitter"

[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#go"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
